spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,
      p6spy: true
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/weasel8?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&tinyInt1isBit=false&autoReconnect=true&rewriteBatchedStatements=true
          username: root
          password: root
        postgresql:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://127.0.0.1:5432/jeecg-boot
          username: postgres
          password: postgres
        slave_2:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/weasel8?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&tinyInt1isBit=false&autoReconnect=true&rewriteBatchedStatements=true
          username: root
          password: root
  redis:
    host: localhost
    database: 1
    password:
